#!/usr/bin/env zsh

# occ - OnChange Commands - wrapper for the 'onchange' npm package.

case "$1" in
    # ------------------------------------------------------------------------
    # Reference: https://prettier.io/docs/en/watching-files.html
    watch)
        # watch folder for changes and run prettier as needed
        npx onchange '**/*.js' -- npx prettier --write {{changed}}
        ;;

    # ------------------------------------------------------------------------
    # Reference for remaining options: https://www.npmjs.com/package/onchange

    test)
        # On every change run `npm test`.
        onchange 'app/**/*.js' 'test/**/*.js' -- npm test
        ;;

    restart)
        # On every change restart `server.js` (by killing the running process).
        onchange -i -k '**/*.js' -- node server.js
        ;;

    echo)
        # On every change `echo` file change.
        onchange '**/*.js' -- echo '{{event}} to {{changed}}'
        ;;

    *)
        echo "Usage: occ [watch | test | restart | echo]"
        ;;
esac
